### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by mkormendy** [kiteco/sublimetext2-plugin#2]
Instructions for installing would be nice. Maybe even pushed to the sublime package manager repo?

**Comment by Nisthar** [comment]
I think this is dead. Would have been a great tool for developers.

**Comment by Nisthar** [comment]
@mkormendy Did you got it fixed?

**Comment by mkormendy** [comment]
I use something else .. It's called Dash, it's a Documentation Browser for 150+ APIs https://kapeli.com/dash

**Comment by Nisthar** [comment]
Unfortunately, its only for macOS, I think

**Comment by adamsmith** [comment]
Unfortunately Kite doesn't support ST2 any longer.  If you use ST3 then Kite should work out of the box but let me know if there are any issues.

RE Kite vs Dash, they are fairly different products.  I'm biased, but Kite has much more documentation coverage than Dash, but more importantly includes other features like ranked completions.

**Comment by Nisthar** [comment]
@adamsmith Are you saying that sublime text 3 doesn't need any plugin for kite to work?
I open the kite application. But it doesn't show any autocompletion or anything. It's only recognising my pycharm and vs code editors.

**Comment by adamsmith** [comment]
@Nisthar Kite has a Sublime Text 3 plugin which it gives you the option to install when you install Kite.  (The only exception to this is if you install Kite via autocomplete-python in Atom.)

It sounds like, with Kite installed, if you go to http://localhost:46624/settings/plugins it says that Sublime Text 3 is not installed, but it is?  If this is the case, a few questions:

* which OS, and version of OS are you running?
* where is Sublime Text 3 installed?

Thanks for your help!

(cc @jansorg)
