### ISSUE TITLE
[Feature request] Support portable Sublime Text

### ISSUE THREAD

**Issue by Kristinita** [kiteco/sublimetext2-plugin#3]
### 1. Summary

I can't begin to use Kite in my Sublime Text 3 portable. Possibly, portable version unsupported at the time.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Sublime Text Build 3143 Portable (the latest stable portable version at the time),
+ Kite 1.2018.111.0.

### 3. Steps to reproduce

I download Kite → I create Kite account → I restart Sublime Text.

`Local Settings` → `Plugins` → I see a message:

> We could not find any supported editors on your system. If this is an error, please send a message to feedback@kite.com

![Kite](https://i.imgur.com/KY0zY38.png)

Same result by address **<http://localhost:46624/settings/plugins>**:

![Localhost](https://i.imgur.com/9sFeJ9k.png)

### 4. Not helped

I try install this Kite plugin as any plugin, hosted on GitHub or BitBucket.

`Package Control: Add Repository` → in opened input field I paste `https://github.com/kiteco/sublimetext2-plugin` → `Package Control: Install Package` → I select `sublimetext2-plugin` → <kbd>Enter</kbd> → I restart Sublime Text.

Nothing changed.

### 5. Related issue

+ [**Install Kite plugin in Portable Sublime Text 3**](https://stackoverflow.com/q/43114126/5951529)

Thanks.

**Comment by dhung09** [comment]
Hi @Kristinita - where is your copy of Sublime installed? Is it on the C:\ drive?

**Comment by Kristinita** [comment]
@dhung09 , no, I install portable Sublime Text in `D:\` drive. `D:\Sublime Text 3 x64` — is path.

Thanks.

**Comment by dhung09** [comment]
Unfortunately our plugin installer currently can't recognize installations in the `D:\` drive. You can either:

1. Install Sublime in the `C:\` drive or
2. Install the plugin manually yourself - I can send you the plugin and instructions on how to manually install it

Let me know which method you would prefer! Sorry for the inconvenience.

**Comment by Kristinita** [comment]
@dhung09 

1. I'm sorry, I don't want move Sublime Text do disk `C:\`. Because I use Sublime Text some years and I need to change many settings, that all will works correct.
1. Can you add instructions of installation to documentation or README? For all Kite users, not for me personally.
1. Do you plain support in future installation, if portable Sublime Text not on disk `C:\`?

Thanks.

**Comment by dhung09** [comment]
No problem @Kristinita, I totally understand why you don't want to move your installation.

* I'll update the README.md (this repo is actually deprecated, you can find the updated information [here](https://github.com/kiteco/plugins/tree/master/sublimetext3))
* We're looking into how to get our plugin manager to detect installations outside of `C:\` - hopefully we can fix this soon!

**Comment by dhung09** [comment]
@Kristinita please see [Custom Windows installations](http://help.kite.com/article/62-managing-editor-integrations) to learn how to install the Sublime plugin.

We're tracking this bug on our side, so I'll close this here.
